# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4RmtT9cp7blsVSSlRKVp8bYAmMIOTIH
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.io import wavfile

def generate_spectrogram(wav_file):
    # Read the WAV file
    sample_rate, data = wavfile.read(wav_file)

    # Check if data is stereo or mono
    if len(data.shape) > 1:
        data = data[:, 0]  # Use one channel if stereo

    # Create a spectrogram
    plt.figure(figsize=(12, 6))
    plt.specgram(data, Fs=sample_rate, NFFT=1024, noverlap=512, cmap='inferno')

    plt.title(f'Spectrogram of {wav_file}')
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    plt.colorbar(label='Intensity (dB)')
    plt.xlim(0, len(data) / sample_rate)  # Set x-axis limit
    plt.ylim(0, sample_rate / 2)           # Frequency range from 0 to Nyquist frequency
    plt.grid(True)
    plt.show()

# Example usage
wav_file_path = '0lfsiavgjt7pbeg8o3.wav'  # Replace with your WAV file path
generate_spectrogram(wav_file_path)

import numpy as np
import matplotlib.pyplot as plt
from scipy.io import wavfile

def generate_spectrogram(wav_file):
    # Read the WAV file
    sample_rate, data = wavfile.read(wav_file)

    # Check if data is stereo or mono
    if len(data.shape) > 1:
        data = data[:, 0]  # Use one channel if stereo

    # Create a spectrogram
    plt.figure(figsize=(12, 6))
    plt.specgram(data, Fs=sample_rate, NFFT=1024, noverlap=512, cmap='inferno')

    plt.title(f'Spectrogram of {wav_file}')
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    plt.colorbar(label='Intensity (dB)')
    plt.xlim(0, len(data) / sample_rate)  # Set x-axis limit
    plt.ylim(0, sample_rate / 2)           # Frequency range from 0 to Nyquist frequency
    plt.grid(True)
    plt.show()

# Example usage
wav_file_path = 'A.wav'  # Replace with your WAV file path
generate_spectrogram(wav_file_path)

import numpy as np
import matplotlib.pyplot as plt
from scipy.io import wavfile

def generate_spectrogram(wav_file):
    # Read the WAV file
    sample_rate, data = wavfile.read(wav_file)

    # Check if data is stereo or mono
    if len(data.shape) > 1:
        data = data[:, 0]  # Use one channel if stereo

    # Create a spectrogram
    plt.figure(figsize=(12, 6))
    plt.specgram(data, Fs=sample_rate, NFFT=1024, noverlap=512, cmap='inferno')

    plt.title(f'Spectrogram of {wav_file}')
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    plt.colorbar(label='Intensity (dB)')
    plt.xlim(0, len(data) / sample_rate)  # Set x-axis limit
    plt.ylim(0, sample_rate / 2)           # Frequency range from 0 to Nyquist frequency
    plt.grid(True)
    plt.show()

# Example usage
wav_file_path = 'B.wav'  # Replace with your WAV file path
generate_spectrogram(wav_file_path)

!pip install gtts

from gtts import gTTS
import os

# Matnni belgilash
text = "The Suicidal Tour took place when Brazilian professional football club Santa Cruz Futebol Clube toured the North Region of Brazil from 2 January to 29 April 1943. Over almost four months, they played either 26 or 28 friendly matches in six cities. The tour gained its name due to the misfortunes endured by the club. Looking to recover from a financial crisis, Santa Cruz arranged five matches in Belém, Pará. Traveling up the Amazon River for another round of matches, they first started experiencing problems in Manaus, where two players left to play for other clubs and seven members of the team's delegation caught dysentery. Two players went on to contract typhoid fever and died. Unable to return home through the sea, and needing to cover growing costs, Santa Cruz had to return to Recife by land, playing matches along the way to earn money. The return had further problems, including a fake arrest warrant for a player, a trip alongside thieves, and two train derailments."

# Ovoz yaratish (gTTS - Google Text-to-Speech)
language = 'en'  # Changed to English ('en')
tts = gTTS(text=text, lang=language, slow=False)

# Ovoz faylini saqlash
audio_file = "output.mp3"
tts.save(audio_file)

# Ovoz faylini tinglash (Google Colab-da)
from IPython.display import Audio
Audio(audio_file)

!pip install gtts

from gtts import gTTS
import os

# Matnni belgilash
text = "Over 6 seasons, 110 episodes of the American television sitcom Community aired. The series premiered on NBC on September 17, 2009, and ended on June 2, 2015. Community follows a group of students at a community college in the fictional locale of Greendale, Colorado. The series heavily uses meta-humor and pop culture references, often parodying film and television clichés and tropes. The series stars Joel McHale, Gillian Jacobs, Danny Pudi, Yvette Nicole Brown, Alison Brie, Donald Glover, Ken Jeong, and Chevy Chase, with Jim Rash being promoted from recurring to series regular in season three. The first season of Community aired from September 17, 2009, through May 20, 2010. After four further seasons, NBC announced that the series had been canceled. Yahoo! Screen picked it up for a sixth and final season"

# Ovoz yaratish (gTTS - Google Text-to-Speech)
language = 'en'  # Changed to English ('en')
tts = gTTS(text=text, lang=language, slow=False)

# Ovoz faylini saqlash
audio_file = "output.mp3"
tts.save(audio_file)

# Ovoz faylini tinglash (Google Colab-da)
from IPython.display import Audio
Audio(audio_file)

!pip install gtts

from gtts import gTTS
import os

# Matnni belgilash
text = "I got love I got love, и-и, ха Окутала меня, окутала Ты будто мой сорт мариуанна Небо в алмазах, лето летало Ты моя baby, дочь карнавала Двигайся, крошка, принцесса бала Ночь перемен, мысли растамана Пока не устал, музыка играла Кто-то курил, кого-то впирало Эта дура Дуремара, а нам она Было думал, улетала в тёплые края Лето, море, песок, но мне тебя мало Танцую в пол, руки в потолок зала Оттуда, куда пал, больше не вернусь Чудом умотал и забрал с ней грусть Это наша жизнь, и ей всегда мало Танцую в пол, руки в потолок зала Go, everybody, shake your ass, go Move, everybody, моё любимое шоу Голова качала, бочата давала манна, ма Благо болванов, нал и наваров Бутора валом, подавай нам Когда будет этот день, ты пой про себя Про меня, за любовь, за маму, за брат А то судьба загнёт ата-ата Атаман Я типа атаман В жарком танго меломан Мною правит bad man Танцуй, так примитивно Танцуй, так импульсивно Танцуй, дочь карнавала Тут на танцполе тебя было мало, мало I got love, I feel I got you on my mind I got love, my skill My li-li-li-life I got love, I feel I got you on my mind I got love, my skill My li-li-li-life "
# Ovoz yaratish (gTTS - Google Text-to-Speech)
language = 'en'  # Changed to English ('en')
tts = gTTS(text=text, lang=language, slow=False)

# Ovoz faylini saqlash
audio_file = "output.mp3"
tts.save(audio_file)

# Ovoz faylini tinglash (Google Colab-da)
from IPython.display import Audio
Audio(audio_file)